### ISSUE TITLE
I think you guys made an infinite loop or something

### ISSUE THREAD

**Issue by gusals3587** [MCMrARM/mcpelauncher-linux#69] opened 2016-08-31 13:38 UTC
There is about 50 times more code, but I think it is printing the same thing (I'm not a programmer, I'm just a linux enthusiast who just happens to be a teenager wanting to play minecraft pe on linux)
[infinite loop.txt](https://github.com/MCMrARM/mcpelauncher-linux/files/447331/infinite.loop.txt)

**Comment by guppy42** [comment] 2016-09-02 06:43
It's a lot of stack traces, 50 isn't so bad - I get just shy of 300.000 lines when I run it :|

It's been 3 months since the last commit here, so it's entirely possible he has lost interest in the project.


The last MCPE version mentioned in code was 0.15.1 I have been unable to obtain an older version ( current it 0.15.6 ) so I cannot test if that version actually works.

**Comment by DaMatrix** [comment] 2016-09-29 19:04
+1. Happens to me too, with x86 apks from 0.15.0 and 0.15.1. If you want i can send them?

**Comment by guppy42** [comment] 2016-09-30 06:13
I'd love to get my mitten on those but as I've said before there are some copyright issues with linking even to obsolete aps, and we don't want the good people of github to close down the project over infractions :)

**Comment by MCMrARM** [comment] 2016-11-20 11:25
If you run it with --no-stacktrace it will instead just crash instead. The infinite loop is something I am aware of, and might fix it when I find a little bit of free time and update the launcher to the newest version,

**Comment by MCMrARM** [comment] 2017-01-13 13:24
Duplicate of #60

**Closed by MCMrARM** 2017-01-13 13:24 UTC
