### ISSUE TITLE
Sensitivity too fast

### ISSUE THREAD

**Issue by elvaalxv** [MCMrARM/mcpelauncher-linux#250] opened 2017-12-04 15:21 UTC
Allthougt 0, but the sensitivity still too fast. Who can decrease the speed? Thanks for that before

**Comment by coolkidsrule101** [comment] 2017-12-09 17:22
turn it down in mcpe settings

**Comment by MCMrARM** [comment] 2017-12-09 18:24
He said he set it to the lowest setting. Unfortunately, I'm not sure what I should do about it as this seems more of a MCPE bug than mine.

**Comment by coolkidsrule101** [comment] 2017-12-09 19:55
Oh ouch ok
Hopefully they fix it

**Comment by MCMrARM** [comment] 2018-01-12 16:11
Duplicate of https://github.com/MCMrARM/mcpelauncher-linux/issues/88

**Closed by MCMrARM** 2018-01-12 16:11 UTC
