### ISSUE TITLE
how to install in ubuntu

### ISSUE THREAD

**Issue by Varfalomey** [MCMrARM/mcpelauncher-linux#34] opened 2016-03-05 09:39 UTC
how? i dont know

**Comment by Varfalomey** [comment] 2016-03-05 09:45
egor@egor-R425D-R525D:~$   sudo apt-get install cmake zlib1g-dev:i386 libncurses5-dev:i386 libgles2-mesa-dev gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 linux-libc-dev:i386 uuid-dev:i386 libpng-dev:i386 libx11-dev:i386
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Note, selecting 'libpng12-dev:i386' instead of 'libpng-dev:i386'
cmake is already the newest version.
g++-multilib is already the newest version.
gcc-multilib is already the newest version.
libncurses5-dev:i386 is already the newest version.
libx11-dev:i386 is already the newest version.
zlib1g-dev:i386 is already the newest version.
libgles2-mesa-dev is already the newest version.
libpng12-dev:i386 is already the newest version.
linux-libc-dev:i386 is already the newest version.
uuid-dev:i386 is already the newest version.
Следующий пакет устанавливался автоматически и больше не требуется:
  efibootmgr firefox-locale-en firefox-locale-ru libatk1.0-0:i386
  libatkmm-1.6-1 libcairo2:i386 libcairomm-1.0-1 libdbus-glib-1-2:i386
  libgdk-pixbuf2.0-0:i386 libglade2-0:i386 libglibmm-2.4-1c2a libgtk2.0-0:i386
  libjasper1:i386 libmp3lame0:i386 libpango1.0-0:i386 libpangocairo-1.0-0:i386
  libpangomm-1.4-1 libpixman-1-0:i386 libsigc++-2.0-0c2a libtheora0:i386
  libtimezonemap1 libxcb-render0:i386 libxcb-shm0:i386 libxmu6:i386
  linux-headers-3.19.0-26 linux-headers-3.19.0-26-generic
  linux-image-3.19.0-26-generic linux-image-extra-3.19.0-26-generic sbsigntool
  scrollkeeper secureboot-db
Для его удаления используйте «apt-get autoremove».
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 52 пакетов не обновлено.
egor@egor-R425D-R525D:~$ chmod -R 777 /home/egor/mcpelinux
egor@egor-R425D-R525D:~$ cmake /home/egor/mcpelinux
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PNG (missing: PNG_LIBRARY) (found version "1.2.50")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindPNG.cmake:105 (find_package_handle_standard_args)
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/egor/CMakeFiles/CMakeOutput.log".
See also "/home/egor/CMakeFiles/CMakeError.log".
egor@egor-R425D-R525D:~$

**Comment by Varfalomey** [comment] 2016-03-05 10:12
i fixed

**Comment by Varfalomey** [comment] 2016-03-05 10:12
new problem:

egor@egor-R425D-R525D:~/minecraftpe$ make
Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f9): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
make[2]: *** [mcpelauncher] Error 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

**Comment by svilex** [comment] 2016-03-23 12:06
@Varfalomey @MCMrARM same here #38

**Comment by MCMrARM** [comment] 2016-06-19 13:11
Duplicate of #10

**Closed by MCMrARM** 2016-06-19 13:11 UTC
