### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by TheClimbing** [MCMrARM/mcpelauncher-linux#26] opened 2016-02-26 14:10 UTC
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3a3): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x382): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:538: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

Got this any help?

**Comment by MCMrARM** [comment] 2016-03-01 19:45
Install 32 bit GPU driver compatibility libs

**Comment by MCMrARM** [comment] 2016-06-19 13:12
Duplicate of #10

**Closed by MCMrARM** 2016-06-19 13:12 UTC
