### ISSUE TITLE
Armhf 32 bit support?

### ISSUE THREAD

**Issue by TheForgottenKing** [MCMrARM/mcpelauncher-linux#149] opened 2017-07-25 22:05 UTC
How can I make this run on an arm machine? Samsung Chromebook 2012 arm32

**Comment by MCMrARM** [comment] 2017-07-27 17:25
Currently running thiis on ARM bit machines is not support.

**Comment by kris27mc** [comment] 2017-07-31 19:48
I doubt this will help in _ANY_ way but... there is an [old project for Raspberry Pi](https://github.com/ryanterry131/mcpelauncher-pi), so if you have any coding knowledge, maybe you could study that and attempt something?

**Comment by MCMrARM** [comment] 2017-08-07 12:34
Duplicate of #20.

**Closed by MCMrARM** 2017-08-07 12:34 UTC
