### ISSUE TITLE
Blackscreen and crash

### ISSUE THREAD

**Issue by MrGenga** [MCMrARM/mcpelauncher-linux#64] opened 2016-08-25 14:32 UTC
@MCMrARM There is log:
```/lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#15 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#16 [0xf773abc0]
#17 [0xf773abe9]
#18 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#20 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#21 [0xf773abc0]
#22 [0xf773abe9]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]

Signal 6 received
Getting stacktrace...
Backtrace elements: 25
#0 ./minecraftle(_Z12handleSignali+0x47) [0x8062ba9]
#1 [0xf773abc0]
#2 [0xf773abe9]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#5 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#6 [0xf773abc0]
#7 [0xf773abe9]
#8 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#9 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#10 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#11 [0xf773abc0]
#12 [0xf773abe9]
#13 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#14 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#15 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#16 [0xf773abc0]
#17 [0xf773abe9]
#18 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#20 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#21 [0xf773abc0]
#22 [0xf773abe9]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]

Signal 6 received
Getting stacktrace...
Backtrace elements: 25
#0 ./minecraftle(_Z12handleSignali+0x47) [0x8062ba9]
#1 [0xf773abc0]
#2 [0xf773abe9]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#5 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#6 [0xf773abc0]
#7 [0xf773abe9]
#8 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#9 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#10 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#11 [0xf773abc0]
#12 [0xf773abe9]
#13 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#14 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#15 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#16 [0xf773abc0]
#17 [0xf773abe9]
#18 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#20 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#21 [0xf773abc0]
#22 [0xf773abe9]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]

Signal 6 received
Getting stacktrace...
Backtrace elements: 25
#0 ./minecraftle(_Z12handleSignali+0x47) [0x8062ba9]
#1 [0xf773abc0]
#2 [0xf773abe9]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#5 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#6 [0xf773abc0]
#7 [0xf773abe9]
#8 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#9 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#10 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#11 [0xf773abc0]
#12 [0xf773abe9]
#13 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#14 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#15 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#16 [0xf773abc0]
#17 [0xf773abe9]
#18 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]
#20 ./minecraftle(_Z18detachFromJavaStubv+0) [0x8062d81]
#21 [0xf773abc0]
#22 [0xf773abe9]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf71fae89]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf71fc3e7]```

**Comment by MCMrARM** [comment] 2017-01-13 13:30
Duplicate of #60

**Closed by MCMrARM** 2017-01-13 13:30 UTC
