### ISSUE TITLE
Make fails after cmake successfully runs, /usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by DanielTurner** [MCMrARM/mcpelauncher-linux#23] opened 2016-02-07 01:33 UTC
This seems like an issue finding open gl drivers, but it is difficult to pin down the issue.

cmake runs successfully, but the output of make is as follows.

Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f7): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d6): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
make[2]: *** [mcpelauncher] Error 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

The drivers are nvidia (Quadro FX 570) and I think that may be the issue, it is an older machine.
The machine is running Ubuntu 14.04.
Is there a way to run this headless without the graphics card as I am only try to run this as a server so the kids can connect their tablets? Or has anyone overcome this issue already.

Thanks.
Daniel.

**Comment by MCMrARM** [comment] 2016-02-20 10:27
Please reinstall GPU drivers and install 32 bit compatibility libs.

**Comment by MCMrARM** [comment] 2016-06-19 13:13
Duplicate of #10

**Closed by MCMrARM** 2016-06-19 13:13 UTC
