### ISSUE TITLE
Issue when updated to 1.2.6

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#254] opened 2017-12-09 11:15 UTC
when i want to start mcpe i get this: 
`denis@denis-HP-Compaq-dc5700-Microtower:~$ mcpelauncher
loading native libraries
oslib: libGLESv2.so.2: 41981184
oslib: /usr/local/share/mcpelauncher/libs/native/libfmod.so.9.6: 41963632
oslib: libm.so.6: -1210193488
loading hybris libraries
loading MCPE
loaded MCPE (at 2845728768)
apply patches
original: 85 83 87 86 131
post patch: 233 192 167 253 85
original: 85 83 87 86 131
post patch: 233 217 105 254 85
original: 85 83 87 86 129
post patch: 233 61 103 254 85
original: 83 87 86 131 236
post patch: 233 255 103 254 85
original: 83 131 236 8 232
post patch: 233 251 232 45 84
original: 83 87 86 131 236
post patch: 233 29 240 45 84
original: 85 83 87 86 129
post patch: 233 163 212 35 84
original: 85 83 87 86 129
post patch: 233 41 153 92 84
original: 85 83 87 86 129
post patch: 233 154 165 92 84
original: 85 83 87 86 129
post patch: 233 231 152 92 84
original: 85 83 87 86 129
post patch: 233 233 16 92 84
original: 85 83 87 86 129
post patch: 233 125 17 92 84
original: 85 83 87 86 129
post patch: 233 220 238 93 84
original: 83 87 86 131 236
post patch: 233 79 157 92 84
original: 85 83 87 86 129
post patch: 233 49 187 92 84
patches applied!
Version: 1.2.6
init app platform vtable
AppPlatform size = 182
init app platform
app platform initialized
init window
EGL_VERSION = 1.4 (DRI2)
144 144
create device id: 
create minecraft client
userdata path = /home/denis/.local/share/mcpelauncher/
get system region: 0xdeadbeef
current storage path = /home/denis/.local/share/mcpelauncher/
userdata path = /home/denis/.local/share/mcpelauncher/
init minecraft client
get assert full path: uniforms.json
userdata path = /home/denis/.local/share/mcpelauncher/
userdata path = /home/denis/.local/share/mcpelauncher/
current storage path = /home/denis/.local/share/mcpelauncher/
get data url: /home/denis/.local/share/mcpelauncher/assets/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
xbox read config file
get assert full path: texture_backwards_compatibility_mapping.json
get assert full path: texture_backwards_compatibility_mapping.json
userdata path for levels = /home/denis/.local/share/mcpelauncher/
userdata path for levels = /home/denis/.local/share/mcpelauncher/
internal storage path = /home/denis/.local/share/mcpelauncher/
userdata path = /home/denis/.local/share/mcpelauncher/
[MTU] Max MTU Size 1492 bytes
[MTU] Max MTU Size 1492 bytes
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
get data url: /home/denis/.local/share/mcpelauncher/assets/
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
get assert full path: profanity_filter.wlist
internal storage path = /home/denis/.local/share/mcpelauncher/
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get product sku prefix: 
allows subscriptions: true
get user access token async
handle license changed
Signal 11 received
Backtrace elements: 3
#0 /usr/local/share/mcpelauncher/bin/mcpelauncher(_Z12handleSignaliPv+0x70) [0x747ab9]
#1 [0xb7fb5d04]
#2 HYBRIS Social::MultiplayerService::setServiceManager(Social::MultiplayerServiceManager&)+8 in libminecraftpe.so+0x1919ff8 [0xab2ffff8]
Dumping stack...
#17 HYBRIS Social::MultiplayerService::setServiceManager(Social::MultiplayerServiceManager&)+8 in libminecraftpe.so+0x1919ff8 [0xab2ffff8]
#64 HYBRIS Social::MultiplayerService::setServiceManager(Social::MultiplayerServiceManager&)+8 in libminecraftpe.so+0x1919ff8 [0xab2ffff8]
#92 HYBRIS PurchaseCache::PurchaseCache(std::string, std::string)+183 in libminecraftpe.so+0x1525167 [0xaaf0b167]
#400 HYBRIS Social::MultiplayerServiceManager::RegisterServiceList(std::vector<std::shared_ptr<Social::MultiplayerService>, std::allocator<std::shared_ptr<Social::MultiplayerService> > >)+78 in libminecraftpe.so+0x14097ae [0xaadef7ae]
#408 HYBRIS MinecraftGame::initImpl()+13876 in libminecraftpe.so+0xdb6304 [0xaa79c304]
#428 HYBRIS ServiceLocator<AppPlatform>::mService+0 in libminecraftpe.so+0x3886ddc [0xad26cddc]
#624 HYBRIS MinecraftGame::_initMinecraftGame()+1244 in libminecraftpe.so+0xdadf1c [0xaa793f1c]
#670 HYBRIS (null)+0 in libminecraftpe.so+0x394d22c [0xad33322c]
#683 HYBRIS getTimeMs()+0 in libminecraftpe.so+0x24b9230 [0xabe9f230]
#685 HYBRIS std::_Function_base::_Base_manager<int (*)()>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)+0 in libminecraftpe.so+0xde5740 [0xaa7cb740]
#686 HYBRIS std::_Function_handler<int (), int (*)()>::_M_invoke(std::_Any_data const&)+0 in libminecraftpe.so+0xde5720 [0xaa7cb720]
#687 HYBRIS getTimeMs()+0 in libminecraftpe.so+0x24b9230 [0xabe9f230]
#689 HYBRIS std::_Function_base::_Base_manager<int (*)()>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)+0 in libminecraftpe.so+0xde5740 [0xaa7cb740]
#690 HYBRIS std::_Function_handler<int (), int (*)()>::_M_invoke(std::_Any_data const&)+0 in libminecraftpe.so+0xde5720 [0xaa7cb720]
#692 HYBRIS (null)+0 in libminecraftpe.so+0x394d2f0 [0xad3332f0]
#693 HYBRIS std::_Function_base::_Base_manager<double (*)()>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)+0 in libminecraftpe.so+0xc46940 [0xaa62c940]
#694 HYBRIS std::_Function_handler<double (), double (*)()>::_M_invoke(std::_Any_data const&)+0 in libminecraftpe.so+0xc46920 [0xaa62c920]
#704 HYBRIS App::init(AppContext&)+36 in libminecraftpe.so+0x1a58054 [0xab43e054]
#706 HYBRIS (null)+0 in libminecraftpe.so+0x394d358 [0xad333358]
#746 HYBRIS xbox::services::java_interop::log_cll(std::string const&, std::string const&, std::string const&)+0 in libminecraftpe.so+0x2788df0 [0xac16edf0]
#747 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x3944328 [0xad32a328]
Signal 6 received
Abgebrochen (Speicherabzug geschrieben)
denis@denis-HP-Compaq-dc5700-Microtower:~$ 
`
I have Lubuntu 17.10 or 0.4 idk

**Comment by Encritary** [comment] 2017-12-09 13:10
Duplicate

**Comment by MCMrARM** [comment] 2017-12-09 13:38
Duplicate of #252

**Closed by MCMrARM** 2017-12-09 13:38 UTC
