### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by andrusdiaz** [MCMrARM/mcpelauncher-linux#62] opened 2016-07-20 22:42 UTC
Hi I'm Spanish speaking so here sorry if I have errors. when putting the command make jumps these two errors in linuxmint 18(  CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f8): warning: the use of`pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function`my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): warning: the use of `pthread_attr_setstackaddr' is deprecated, use`pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:581: recipe for target 'mcpelauncher' failed
make[2]: **\* [mcpelauncher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: **\* [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2
)   I do please the error says there is a dependency as I fix

**Comment by guppy42** [comment] 2016-08-26 07:54
According to the docs and other similar issues - your missing the EGL:i386 library .

supposedly the fix is to reinstall the graphics drivers, but switching between the Nouveau and Nvidia driver via the Ubuntu driver tool did not solve the issue for me.

Any clarification on exactly how your supposed to install the driver to solve the issue would be nice

**Comment by guppy42** [comment] 2016-08-26 21:47
For ubuntu 16.04 ( think mint 18 is based on this ? ) i fumbled my way to a solution;

sudo apt-get install libegl1-mesa:i386
sudo apt-get install libegl1-mesa-dev:i386


if the second command fails - do these in order untill you no longer get unmet dependencies;

sudo apt-get install libegl1-mesa-drivers
sudo apt-get install libwayland-egl1-mesa:i386
sudo apt-get install libwayland-dev:i386
sudo apt-get install libmirclient-dev:i386
sudo apt-get install libxkbcommon-dev:i386
sudo apt-get install libmircommon-dev:i386
sudo apt-get install libmirclient-dev:i386

and finally do 

sudo apt-get install libegl1-mesa-dev:i386

In theory you could combine it into one big command like;


sudo apt-get install libmirclient-dev:i386 libmircommon-dev:i386 libxkbcommon-dev:i386 libmirclient-dev:i386 libwayland-dev:i386 libwayland-egl1-mesa:i386 libegl1-mesa-drivers libegl1-mesa-dev:i386 libegl1-mesa:i386


But I can't test that with out doing a re-install ;)

after all this run make again

**Comment by MCMrARM** [comment] 2017-01-13 13:25
Duplicate of #61

**Closed by MCMrARM** 2017-01-13 13:25 UTC
