### ISSUE TITLE
Weird log out of "make" command

### ISSUE THREAD

**Issue by iksaku** [MCMrARM/mcpelauncher-linux#17] opened 2015-11-16 03:28 UTC
I have installed all dependencies listed in `README.md` file and also the ones mentioned in issue #8, still getting some errors.

 - [Log from `make` command](http://pastebin.com/SCJuJYAC)
 - [Log at `./mcpelauncher`](http://pastebin.com/2jFfCDku)

OS: Ubuntu 15.04, "everything updated"

**Comment by InusualZ** [comment] 2015-11-16 03:48
Seems that your binary of fmod is broken. Or you os is incompatible or something

**Comment by iksaku** [comment] 2015-11-16 03:49
Hmm, using Ubuntu 15.04...

**Comment by InusualZ** [comment] 2015-11-16 06:56
What abot your sound device driver?

**Comment by iksaku** [comment] 2015-11-16 06:57
Wut? Well, I don't know about it... It works perfectly with all other apps

**Comment by MCMrARM** [comment] 2015-12-06 18:37
Duplicate of #14

**Closed by MCMrARM** 2015-12-06 18:37 UTC
