### ISSUE TITLE
Gameplay issues (1.0.0)

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#92] opened 2017-01-04 19:20 UTC
Sometimes it random hits when moving
If I press Shift button to sneak it keeps sneaking after I release the button: I have to press Esc/E/T button for it to return "unpressed"
Random lags when typing
When returning in-game from start menu or inventory screen it ALWAYS hits what is in the crosshair.
Tab doesn't work correctly (it places a strange O char)

**Comment by MCMrARM** [comment] 2017-01-08 14:38
Tab issue is now fixed, I can't confirm anything else.

**Comment by AryToNeX** [comment] 2017-01-08 15:06
@MCMrARM in latest build you can't even press shift or control to sneak or sprint. If you walk meanwhile you are looking at something the rotation goes mad. But at least tab is now fixed!

**Comment by MCMrARM** [comment] 2017-01-08 16:01
Oh yep I broke special keys I see.. Fixing it now.

**Comment by MCMrARM** [comment] 2017-01-08 16:04
Fixed the shift key, I remapped it to another key by mistake.

**Comment by MCMrARM** [comment] 2017-01-08 19:50
"When returning in-game from start menu or inventory screen it ALWAYS hits what is in the crosshair."
this seems to be a MCPE bug, also it only uses the hit animation, but doesn't actually hit anything. Confirmed by testing in MCPE and enabling Desktop GUIs in settings.

**Comment by MCMrARM** [comment] 2017-01-13 12:54
I'm going to close this for now; there are multiple issues in a single issue. It's hard to manage it this way. Please open a separate issue for each of your problems.

**Closed by MCMrARM** 2017-01-13 12:54 UTC
Labels: invalid
