### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by KennFatt** [MCMrARM/mcpelauncher-linux#135] opened 2017-06-22 18:17 UTC
```
kennan@KENNAN:~/MinecraftPE/mcpelauncher-linux$ ./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 1463619296
oslib: /home/kennan/MinecraftPE/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1463621280
loading hybris libraries
loading MCPE
Illegal instruction (core dumped)
kennan@KENNAN:~/MinecraftPE/mcpelauncher-linux$ ./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 1449643744
oslib: /home/kennan/MinecraftPE/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1449645728
loading hybris libraries
loading MCPE
loaded MCPE (at 4088881152)
apply patches
original: 85 83 87 86 131
post patch: 233 133 72 216 97
original: 85 83 87 86 131
post patch: 233 126 22 217 97
original: 85 83 87 86 129
post patch: 233 226 19 217 97
original: 83 87 86 131 236
post patch: 233 164 20 217 97
original: 83 131 236 8 232
post patch: 233 202 51 113 96
original: 83 87 86 131 236
post patch: 233 236 58 113 96
original: 85 83 87 86 131
post patch: 233 210 164 101 96
original: 83 87 86 131 236
post patch: 233 152 124 145 96
original: 83 131 236 8 232
post patch: 233 174 111 145 96
original: 83 131 236 8 232
post patch: 233 190 110 145 96
original: 83 86 131 236 20
post patch: 233 48 182 202 97
patches applied!
init app platform vtable
AppPlatform size = 143
init app platform
app platform initialized
init window
EGL_VERSION = 1.4 (DRI2)
fetch patch notes
create minecraft client
current storage path = data/current/
userdata path = data/user/
userdata path = data/user/
init minecraft client
userdata path = data/user/
userdata path = data/user/
get data url: assets/
internal storage path = data/private/
internal storage path = data/private/
userdata path = data/user/
userdata path = data/user/
get assert full path: uniforms.json
get data url: assets/
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
internal storage path = data/private/
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
get product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
restore from cache
register license change callback
userdata path = data/user/
get store id: LinuxStore
get sub platform store id: LinuxStore
get system region: 0xdeadbeef
xbox get app config singleton
xbox config: set sandbox (stub)
xbox get app config singleton
xbox config: set sandbox (stub)
get assert full path: commands/pregame.json
userdata path for levels = data/user/
internal storage path = data/private/
is tablet = true
get system region: 0xdeadbeef
application id = com.mojang.minecraftpe
userdata path for levels = data/user/
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0


initialized lib
initialized display
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0


send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
get system region: 0xdeadbeef
send http request
destroying http request
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
verifycertchain
Illegal instruction (core dumped)
```
Branch: 1.1
MCPE: 1.1.0.55 (x86)

**Comment by guppy42** [comment] 2017-06-23 06:55
I've run all of these version successfully on the 1.1 branch;

- 1.1.0.9 ( 1.1. beta 7 )
- 1.1.0.53 (1.1 final)
- 1.1.1.0 ( 1.1.1 beta 1)

I don't know the 1.1.0.55 version the current version is 1.1.1.51 ( 1.1.1 final ) which I've yet to test it.

Are you using the 1.1 branch from MCMrARM or my (defunct) fork?

You may know this already, but just to make sure; to get the official 1.1 branch you have to;
```
git clone https://github.com/MCMrARM/mcpelauncher-linux.git
cd mcpelauncher-linux
git checkout 1.1

```

and after that you can do the usual configure/compile dance

**Comment by KennFatt** [comment] 2017-06-23 08:54
@guppy42 okay, i will try another version of MCPE

**Comment by KennFatt** [comment] 2017-06-23 09:05
i've tried with 1.1.0.55 (1.1 final) and 1.1.1.0 (1.1.1 beta 1) just stucked ad xbox popup and forced close, i will try another one

**Comment by KennFatt** [comment] 2017-06-23 09:21
this is log with mcpe version 1.1.0.8

```
loading native libraries
oslib: libGLESv2.so: 1460006624
oslib: /home/kennan/MinecraftPE/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1460008608
loading hybris libraries
loading MCPE
loaded MCPE (at 4089417728)
apply patches
original: 85 83 87 86 131
post patch: 233 229 225 206 97
original: 85 83 87 86 131
post patch: 233 206 175 207 97
original: 85 83 87 86 129
post patch: 233 50 173 207 97
original: 83 87 86 131 236
post patch: 233 244 173 207 97
original: 83 131 236 8 232
post patch: 233 74 193 108 96
original: 83 87 86 131 236
post patch: 233 108 200 108 96
original: 85 83 87 86 131
post patch: 233 146 42 97 96
original: 83 87 86 131 236
post patch: 233 104 11 141 96
original: 83 131 236 8 232
post patch: 233 126 254 140 96
original: 83 131 236 8 232
post patch: 233 142 253 140 96
original: 83 86 131 236 20
post patch: 233 128 153 193 97
patches applied!
init app platform vtable
AppPlatform size = 143
init app platform
app platform initialized
init window
EGL_VERSION = 1.4 (DRI2)
fetch patch notes
create minecraft client
current storage path = data/current/
userdata path = data/user/
userdata path = data/user/
init minecraft client
userdata path = data/user/
userdata path = data/user/
get data url: assets/
internal storage path = data/private/
userdata path = data/user/
userdata path = data/user/
get assert full path: uniforms.json
get data url: assets/
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
internal storage path = data/private/
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
get product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
restore from cache
register license change callback
userdata path = data/user/
get store id: LinuxStore
get sub platform store id: LinuxStore
get assert full path: commands/pregame.json
xbox get app config singleton
xbox config: set sandbox (stub)
xbox get app config singleton
xbox config: set sandbox (stub)
userdata path for levels = data/user/
internal storage path = data/private/
is tablet = true
get system region: 0xdeadbeef
application id = com.mojang.minecraftpe
userdata path for levels = data/user/
userdata path = data/user/
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0



initialized lib
initialized display
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0



Illegal instruction (core dumped)
```

**Comment by guppy42** [comment] 2017-06-23 09:42
Some people do seem to crash when they press the x of the xbox popup  - you can remove it by adding this;

game_haseverloggedintoxbl:0
game_haschosennottosignintoxbl:1

to the user config - I don't recall where the files is stored but doing `grep -nR game_haseverloggedintoxbl` should give you the file name.

But the above error does look a lot like your not in fact using the 1.1 branch of mcpelauncer-linux, can you confirm that you have checked that one out and compile it?

**Comment by KennFatt** [comment] 2017-06-23 14:14
git clone -b 1.1 <link to clone>

**Comment by guppy42** [comment] 2017-06-24 07:36
Odd I just tested with the new version 1.1.2 (1.1.2.50 - com.mojang.minecraftpe 872010250.apk ) and it still works perfectly for me.

What your cpu & gfx model ?

This is the compile version I use ( ubuntu 16.04, i5, nvidia );

https://www.sendspace.com/file/lcjehz

Does that crash the same way for you? - if so it seems to be system specific

**Comment by guppy42** [comment] 2017-06-24 07:55
That is only the launcher - you will still need to extract the apk after extracting the tar.gz

**Comment by KennFatt** [comment] 2017-06-24 09:34
@guppy42 thanks! i'll try it on my  old PC, Lubuntu 64-bit Intel Pentium D 3.4GHz 2 core with ATI Radeon X300 series. im aware i cant run it on that monster

**Comment by KennFatt** [comment] 2017-06-24 09:53
sadly, i had same ending, bit ANDROID_ROOT blabla

**Comment by KennFatt** [comment] 2017-06-24 09:55
```
internal storage path = data/private/
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
get product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxget product sku prefix: linuxallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
get product sku prefix: realmsallows subscriptions: false
restore from cache
register license change callback
userdata path = data/user/
get store id: LinuxStore
get sub platform store id: LinuxStore
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
getjvmenv
xbox get app config singleton
xbox config: set sandbox (stub)
xbox get app config singleton
xbox config: set sandbox (stub)
get assert full path: commands/pregame.json
userdata path for levels = data/user/
internal storage path = data/private/
is tablet = true
get system region: 0xdeadbeef
application id = com.mojang.minecraftpe
userdata path for levels = data/user/
userdata path = data/user/
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0


initialized lib
initialized display
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
send http request
destroying http request
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0


Illegal instruction (core dumped)
```
when i try to use ur method: game_haschosennottosignintoxbl:1

**Comment by guppy42** [comment] 2017-06-24 12:32
Does the user you run the game as have permissions to write to the directory the game is in?

Go to 'Settings' > 'Profile' > 'File storage location' and set it to something else ( should be 'application' by default )

Otherwise please tell me the EXACT steps to reproduce

**Comment by MCMrARM** [comment] 2017-08-07 12:45
Duplicate of #103. If possible, provide with output from `valgrind`, preferably on the linked issue.

**Closed by MCMrARM** 2017-08-07 12:45 UTC
