### ISSUE TITLE
Error when loading hybris libraries

### ISSUE THREAD

**Issue by TheBrokenRail** [MCMrARM/mcpelauncher-linux#91] opened 2016-12-30 16:43 UTC
First Overwritten all conflicting files with compatibility libraries and I got this:
```bash
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 138825416
oslib: /home/[USER]/Downloads/MCPE/Compatibility/MCPE Launcher/(Compiled)/libs/native/libfmod.so.8.2: 138827592
Illegal instruction (core dumped)
```
Then I deleted all libraries except mcpe and got this:
```
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 136994504
oslib: /home/[USER]/Downloads/MCPE/Compatibility/MCPE Launcher (Compiled)/libs/native/libfmod.so.8.2: 136996680
failed to load library libGLESv1_CM.so: Cannot load library: load_library[1109]: Library '/home/[USER]/Downloads/MCPE/Compatibility/MCPE Launcher (Compiled)/libs/libGLESv1_CM.so' not found
```

**Comment by InusualZ** [comment] 2016-12-30 17:00
How do you expect to draw anything to screen if you have deleted the library responsible to draw stuff.
The crashlog say `failed to load library libGLESv1_CM.so`

**Comment by TheBrokenRail** [comment] 2016-12-30 17:04
I tried it without deleting it but then I get the first error.

**Comment by InusualZ** [comment] 2016-12-30 17:11
Are you sure that you have downloaded the x86 version of MCPE? And putted the correct libraries in the correct folder?

**Comment by TheBrokenRail** [comment] 2016-12-30 17:23
Yep, the version of mcpe and I put the librairies in the libs folder


________________________________

**Comment by MCMrARM** [comment] 2017-01-08 17:37
What is your OS/architecture?

**Comment by TheBrokenRail** [comment] 2017-01-08 17:51
Ubuntu 16.04 LTS 32bit


________________________________

**Comment by DaMatrix** [comment] 2017-01-08 18:33
I've actually just done a fresh install of Ubuntu 16.04, so I'll run a test of this before installing/changing anything else.

**Comment by MCMrARM** [comment] 2017-01-08 19:47
Ubuntu 16.04 LTS 32bit.. What is your CPU?

**Comment by TheBrokenRail** [comment] 2017-01-08 21:50
Pentium 4


________________________________

**Comment by MCMrARM** [comment] 2017-01-13 13:10
Duplicate of #14, check #94.

**Closed by MCMrARM** 2017-01-13 13:10 UTC
Labels: bug
